### ISSUE TITLE
Quad support?

### ISSUE THREAD

**Issue by ngoldbaum** [conda-forge/sleef-feedstock#8]
### Comment:

Is there any particular reason why SLEEF isn't built with `SLEEF_BUILD_QUAD`? If not, would you be open to a PR that adds it to the build?

**Comment by bluescarni** [comment]
No reason except inertia :) quad support is available since 3.6 right?

Of course, feel free to open a PR.

**Comment by ngoldbaum** [comment]
Cool!

@SwayamInSync and I are working on a quad precision float dtype for NumPy. Adding this will make development a lot easier.

**Comment by bluescarni** [comment]
> Cool!
> 
> @SwayamInSync and I are working on a quad precision float dtype for NumPy. Adding this will make development a lot easier.

Ah interesting!

I am the author of a multiprecision math library which includes a wrapper for ``__float128``, called ``real128``:

https://bluescarni.github.io/mppp/real128.html

I have incorporated ``real128`` in another library of mine called ``heyoka.py``, a Python ODE integrator which supports quadruple-precision numerical integrations:

https://bluescarni.github.io/heyoka.py/notebooks/ext_precision.html#quadruple-precision-128-bit-example

Because ``heyoka.py`` makes use of numpy, I had to add support for ``real128`` as a dtype (as shown in the tutorial). Here's the cpp code that adds ``real128`` as a dtype:

https://github.com/bluescarni/heyoka.py/blob/main/heyoka/expose_real128.cpp

I also have support for multiprecision numbers as dtypes:

https://bluescarni.github.io/heyoka.py/notebooks/arbitrary_precision.html

This however comes with a ton of caveats, such as the fact that by default it leaks memory and if you don't want it to leak memory, you have to abuse the custom numpy allocation facilities to enable automatic cleanup of the multiprecision numbers when an array is garbage collected. Here's the cpp code implementing the hack:

https://github.com/bluescarni/heyoka.py/blob/main/heyoka/numpy_memory.cpp

(All of this does not work yet with numpy 2)

**Comment by ngoldbaum** [comment]
Cool!

@seberg wrote a wrapper for GNU multiprecision floats last year using the new DType API: https://github.com/numpy/numpy-user-dtypes/tree/main/mpfdtype

The plan is for Swayam to write one for quad to ultimately maybe possibly use for numpy.float128 instead of the random hodgepodge we get now using long double.

**Comment by bluescarni** [comment]
Thanks for the pointer!

Do you happen to know how @seberg solved the issue of destroying the multiprecision values once an array is garbage collected? I was searching the code for the ``mpfr_clear()`` function, which is the MPFR function for destroying a multiprecision value, but I see it used only once in the ``nextafter()`` implementation:

https://github.com/numpy/numpy-user-dtypes/blob/70626c323cfffa97dd9fb89593f8acf4d5e6e6b8/mpfdtype/mpfdtype/src/ops.hpp#L211

(perhaps I am missing something obvious)

**Comment by bluescarni** [comment]
I think I see it now: in his implementation the precision is set on a per-array basis and that allows him to use the MPFR custom API which does not actually do any memory allocation.

**Comment by seberg** [comment]
Indeed, I avoided external allocations, it's cuter here I think.  But that doesn't mean you can't do it: you just have to implement the proper clearing traversal function.

**Comment by bluescarni** [comment]
Thanks for the reply @seberg !

> But that doesn't mean you can't do it: you just have to implement the proper clearing traversal function.

Do you have a pointer to documentation for this clearing function? Is this something new in the NumPy 2 API?

**Comment by bluescarni** [comment]
That sounds like it:

https://numpy.org/devdocs/reference/c-api/array.html#c.NPY_DT_get_clear_loop

**Comment by ngoldbaum** [comment]
Yup! StringDType uses that too, hopefully implementing it solved most of the issues associated with an array of references.

Maybe let's move this discussion to NumPy or numpy-user-dtypes so it doesn't get lost in this repo.
